<?php
/**
 * README専用多言語辞書
 * Gene-Forge v7.0
 */

function getReadmeLang(): string {
    if (isset($_GET['lang'])) return $_GET['lang'];
    if (isset($_COOKIE['lang'])) return $_COOKIE['lang'];
    return 'ja';
}

function rt(string $key): string {
    static $dict = null;
    if ($dict === null) {
        $lang = getReadmeLang();
        $dict = README_LANG[$lang] ?? README_LANG['ja'];
    }
    return $dict[$key] ?? $key;
}

const README_LANG = [
    'ja' => [
        'title' => 'Gene-Forge v7.0',
        'subtitle' => 'Agapornis Genetics Calculator — ALBS Compliant Edition',
        'description' => 'ラブバード（コザクラインコ / Agapornis roseicollis）の遺伝計算エンジン。<br>14座位・310色以上に対応し、ALBS（African Lovebird Society）Peachfaced部門の命名規則に準拠。',
        
        'features' => '機能一覧',
        
        'feat_db' => '個体管理（個別登録）',
        'feat_db_1' => '個体データベース: 名前・性別・誕生日・血統・遺伝子型を一元管理',
        'feat_db_2' => '128羽デモデータ: 検証用のサンプル個体を搭載',
        'feat_db_3' => '血統書生成: 3世代・5世代の血統書をHTML出力',
        'feat_db_4' => 'インポート/エクスポート: JSON・CSV形式に対応',
        
        'feat_health' => '健康評価（交配リスク判定）',
        'feat_health_1' => '近交係数計算: F値の自動計算',
        'feat_health_2' => 'リスク評価: INO系・パリッド系の近親交配制限チェック',
        'feat_health_3' => '世代制限: 形質別の推奨世代制限を表示',
        
        'feat_planner' => '目標計画（交配経路）',
        'feat_planner_1' => '目標色経路探索: 目標の表現型への育成経路を探索',
        'feat_planner_2' => 'ステップガイド: 必要な交配ステップを自動生成',
        
        'feat_path' => '育成経路（形質発現）',
        'feat_path_1' => '形質別ルート: 特定の形質を発現させるための交配手順',
        'feat_path_2' => '世代数見積もり: 目標達成までの最短世代数を計算',
        
        'feat_calc' => '配合結果（交配期待）',
        'feat_calc_1' => '子孫予測: 親の遺伝子型から子の表現型確率を計算',
        'feat_calc_2' => '14座位対応: 全座位の組み合わせを網羅',
        'feat_calc_3' => '伴性遺伝計算: Z染色体連鎖遺伝の正確な計算（オスのスプリット、メスのヘミ接合）',
        
        'feat_estimate' => '遺伝推計（親型逆推）',
        'feat_estimate_1' => '表現型→遺伝子型: 観察された色から可能な遺伝子型を推定',
        'feat_estimate_2' => '確定/推定の区別: 確実に判定できる座位と推定の座位を明示',
        'feat_estimate_3' => 'テスト交配提案: 不確定な座位を確定するための交配提案',
        
        'feat_family' => '一族推計（血統導出）',
        'feat_family_1' => 'FamilyEstimator V3: 家系図ベースの遺伝子型推論エンジン',
        'feat_family_2' => '多世代推論: 祖父母まで遡った遺伝子型推論',
        'feat_family_3' => '証拠ベース確率: 親・子・兄弟からの拘束条件を統合',
        'feat_family_4' => '家系図UI: ドラッグ&ドロップで血縁関係を構築',
        
        'feat_lang' => '多言語対応',
        'feat_lang_list' => '日本語 / English / Deutsch / Français / Italiano / Español',
        
        'files' => 'ファイル構成',
        'quickstart' => 'クイックスタート',
        'requirements' => '動作要件',
        'req_1' => 'PHP 7.4以上',
        'req_2' => 'Webサーバー（Apache/Nginx）またはPHP内蔵サーバー',
        'installation' => 'インストール',
        'open_browser' => 'ブラウザで <code>http://localhost:8000</code> を開く。',
        
        'examples' => '使用例',
        'example_1' => '子孫計算（PHP）',
        'example_2' => '色名取得',
        'example_3' => '遺伝子型推定',
        'example_4' => '家系図推論（API）',
        'example_4_result' => '結果例: 子にアクアが出現 → 両親とも <code>+aq</code>（アクアスプリット）と推論',
        
        'colors' => '色カテゴリ一覧',
        'col_category' => 'カテゴリ',
        'col_count' => '色数',
        'col_example' => '例',
        
        'genotypes' => '遺伝子型表記法',
        'autosomal' => '常染色体座位',
        'sex_linked' => '伴性座位（Z染色体）',
        'col_locus' => '座位',
        'col_wildtype' => '野生型',
        'col_mutant' => '変異型アレル',
        'col_male_wt' => 'オス野生型',
        'col_male_mut' => 'オス変異型',
        'col_female_wt' => 'メス野生型',
        'col_female_mut' => 'メス変異型',
        
        'demo' => '検証用デモデータ',
        'demo_desc' => 'デモモードには128羽のサンプル個体が含まれており、以下の検証が可能：',
        'demo_health' => '健康評価テスト',
        'demo_health_1' => '父娘交配 → 危険判定（F=25%）',
        'demo_health_2' => '半兄妹交配 → 高リスク判定（F=12.5%）',
        'demo_health_3' => '無関係個体 → 安全判定（F=0%）',
        'demo_genetics' => '遺伝計算テスト',
        'demo_genetics_1' => '伴性遺伝（INO/Opaline/Cinnamon）',
        'demo_genetics_2' => '複対立遺伝子（Parblue系）',
        'demo_genetics_3' => '不完全優性（Dark/Violet）',
        'demo_family' => '家系図推論テスト',
        'demo_family_1' => '子の表現型から親の遺伝子型を逆算',
        'demo_family_2' => 'テスト交配提案の生成',
        
        'license' => 'ライセンス',
        'license_desc' => 'CC BY-NC-SA 4.0 (Creative Commons Attribution-NonCommercial-ShareAlike 4.0)',
        'license_1' => '✅ 個人利用・非商用OK',
        'license_2' => '✅ 改変・再配布OK（同一ライセンス・クレジット表記必須）',
        'license_3' => '❌ 商用利用は要相談',
        
        'contrib' => 'コントリビューション',
        'contrib_desc' => 'Issue・Pull Request 歓迎。',
        'contrib_note' => '特に以下の貢献を募集中：',
        'contrib_1' => '他のラブバード種（A. fischeri, A. personatus 等）への拡張',
        'contrib_2' => '追加言語の翻訳',
        'contrib_3' => 'UI/UX改善',
        'contrib_4' => '遺伝学的知見のフィードバック',
        
        'author' => '作者',
        'author_1' => '制作総指揮: <strong>Shohei Taniguchi</strong>（Homo repugnans）',
        'author_2' => '開発戦術核: <strong>Sirius</strong>（電子精霊）',
        
        'thanks' => '謝辞',
        'thanks_1' => '<strong>ALBS (African Lovebird Society)</strong> — 色名命名規則の参照',
        'thanks_2' => '<strong>世界中のコザクラインコブリーダー</strong> — 遺伝学的知見の蓄積',
        
        'footer_license' => '@license CC BY-NC-SA 4.0 | Commercial use strictly prohibited. | NPO/Educational use welcome.',
        'footer_quote' => '「制度は責任を放棄した。制度外がそれを果たす。」',
        'footer_project' => '制度外文明・かならづプロジェクト',
    ],
    
    'en' => [
        'title' => 'Gene-Forge v7.0',
        'subtitle' => 'Agapornis Genetics Calculator — ALBS Compliant Edition',
        'description' => 'Genetics calculation engine for Lovebirds (Rosy-faced Lovebird / Agapornis roseicollis).<br>Supports 14 loci and 310+ colors, compliant with ALBS (African Lovebird Society) Peachfaced section nomenclature.',
        
        'features' => 'Features',
        
        'feat_db' => 'Bird Management',
        'feat_db_1' => 'Bird Database: Centralized management of name, sex, birthdate, lineage, and genotype',
        'feat_db_2' => '128 Demo Birds: Sample birds for testing',
        'feat_db_3' => 'Pedigree Generation: HTML output for 3 or 5 generation pedigrees',
        'feat_db_4' => 'Import/Export: JSON and CSV format support',
        
        'feat_health' => 'Health Evaluation',
        'feat_health_1' => 'Inbreeding Coefficient: Automatic F-value calculation',
        'feat_health_2' => 'Risk Assessment: INO and Pallid inbreeding restriction checks',
        'feat_health_3' => 'Generation Limits: Recommended limits by trait',
        
        'feat_planner' => 'Target Planner',
        'feat_planner_1' => 'Target Color Pathfinding: Find breeding paths to target phenotypes',
        'feat_planner_2' => 'Step Guide: Auto-generate required breeding steps',
        
        'feat_path' => 'Breeding Path',
        'feat_path_1' => 'Trait Routes: Breeding procedures for specific trait expression',
        'feat_path_2' => 'Generation Estimate: Calculate minimum generations to goal',
        
        'feat_calc' => 'Offspring Calculator',
        'feat_calc_1' => 'Offspring Prediction: Calculate phenotype probabilities from parental genotypes',
        'feat_calc_2' => '14 Loci Support: Covers all locus combinations',
        'feat_calc_3' => 'Sex-Linked Calculation: Accurate Z-chromosome inheritance (male splits, female hemizygous)',
        
        'feat_estimate' => 'Genotype Estimator',
        'feat_estimate_1' => 'Phenotype→Genotype: Estimate possible genotypes from observed colors',
        'feat_estimate_2' => 'Confirmed/Estimated: Distinguish certain loci from inferred ones',
        'feat_estimate_3' => 'Test Breeding Proposals: Suggestions to confirm uncertain loci',
        
        'feat_family' => 'Family Estimator',
        'feat_family_1' => 'FamilyEstimator V3: Pedigree-based genotype inference engine',
        'feat_family_2' => 'Multi-Generation Inference: Trace back to grandparents',
        'feat_family_3' => 'Evidence-Based Probability: Integrate constraints from parents, offspring, siblings',
        'feat_family_4' => 'Family Tree UI: Build relationships with drag & drop',
        
        'feat_lang' => 'Multilingual Support',
        'feat_lang_list' => 'Japanese / English / German / French / Italian / Spanish',
        
        'files' => 'File Structure',
        'quickstart' => 'Quick Start',
        'requirements' => 'Requirements',
        'req_1' => 'PHP 7.4 or higher',
        'req_2' => 'Web server (Apache/Nginx) or PHP built-in server',
        'installation' => 'Installation',
        'open_browser' => 'Open <code>http://localhost:8000</code> in your browser.',
        
        'examples' => 'Usage Examples',
        'example_1' => 'Offspring Calculation (PHP)',
        'example_2' => 'Color Name Retrieval',
        'example_3' => 'Genotype Estimation',
        'example_4' => 'Family Inference (API)',
        'example_4_result' => 'Result: Aqua offspring appears → Both parents inferred as <code>+aq</code> (Aqua split)',
        
        'colors' => 'Color Categories',
        'col_category' => 'Category',
        'col_count' => 'Colors',
        'col_example' => 'Examples',
        
        'genotypes' => 'Genotype Notation',
        'autosomal' => 'Autosomal Loci',
        'sex_linked' => 'Sex-Linked Loci (Z Chromosome)',
        'col_locus' => 'Locus',
        'col_wildtype' => 'Wild Type',
        'col_mutant' => 'Mutant Alleles',
        'col_male_wt' => 'Male Wild',
        'col_male_mut' => 'Male Mutant',
        'col_female_wt' => 'Female Wild',
        'col_female_mut' => 'Female Mutant',
        
        'demo' => 'Demo Data for Testing',
        'demo_desc' => 'Demo mode includes 128 sample birds for the following tests:',
        'demo_health' => 'Health Evaluation Tests',
        'demo_health_1' => 'Father-daughter pairing → Critical (F=25%)',
        'demo_health_2' => 'Half-sibling pairing → High risk (F=12.5%)',
        'demo_health_3' => 'Unrelated birds → Safe (F=0%)',
        'demo_genetics' => 'Genetics Calculation Tests',
        'demo_genetics_1' => 'Sex-linked inheritance (INO/Opaline/Cinnamon)',
        'demo_genetics_2' => 'Multiple alleles (Parblue series)',
        'demo_genetics_3' => 'Incomplete dominance (Dark/Violet)',
        'demo_family' => 'Family Inference Tests',
        'demo_family_1' => 'Reverse-calculate parental genotypes from offspring phenotypes',
        'demo_family_2' => 'Generate test breeding proposals',
        
        'license' => 'License',
        'license_desc' => 'CC BY-NC-SA 4.0 (Creative Commons Attribution-NonCommercial-ShareAlike 4.0)',
        'license_1' => '✅ Personal/Non-commercial use OK',
        'license_2' => '✅ Modification/Redistribution OK (same license, credit required)',
        'license_3' => '❌ Commercial use requires consultation',
        
        'contrib' => 'Contribution',
        'contrib_desc' => 'Issues and Pull Requests welcome.',
        'contrib_note' => 'Especially looking for:',
        'contrib_1' => 'Extension to other Lovebird species (A. fischeri, A. personatus, etc.)',
        'contrib_2' => 'Additional language translations',
        'contrib_3' => 'UI/UX improvements',
        'contrib_4' => 'Genetics knowledge feedback',
        
        'author' => 'Author',
        'author_1' => 'Director: <strong>Shohei Taniguchi</strong> (Homo repugnans)',
        'author_2' => 'Dev Tactical Core: <strong>Sirius</strong> (Electronic Spirit)',
        
        'thanks' => 'Acknowledgments',
        'thanks_1' => '<strong>ALBS (African Lovebird Society)</strong> — Color nomenclature reference',
        'thanks_2' => '<strong>Lovebird breeders worldwide</strong> — Accumulated genetics knowledge',
        
        'footer_license' => '@license CC BY-NC-SA 4.0 | Commercial use strictly prohibited. | NPO/Educational use welcome.',
        'footer_quote' => '"The institution abandoned responsibility. The extra-institutional fulfills it."',
        'footer_project' => 'Extra-Institutional Civilization / Kanarazu Project',
    ],
    
    'de' => [
        'title' => 'Gene-Forge v7.0',
        'subtitle' => 'Agapornis Genetik-Rechner — ALBS-konform',
        'description' => 'Genetik-Berechnungsmaschine für Unzertrennliche (Rosenköpfchen / Agapornis roseicollis).<br>Unterstützt 14 Loci und 310+ Farben, konform mit ALBS (African Lovebird Society) Peachfaced-Nomenklatur.',
        
        'features' => 'Funktionen',
        
        'feat_db' => 'Vogelverwaltung',
        'feat_db_1' => 'Vogeldatenbank: Zentrale Verwaltung von Name, Geschlecht, Geburtsdatum, Linie und Genotyp',
        'feat_db_2' => '128 Demo-Vögel: Testvögel enthalten',
        'feat_db_3' => 'Stammbaum-Erstellung: HTML-Ausgabe für 3 oder 5 Generationen',
        'feat_db_4' => 'Import/Export: JSON- und CSV-Format',
        
        'feat_health' => 'Gesundheitsbewertung',
        'feat_health_1' => 'Inzuchtkoeffizient: Automatische F-Wert-Berechnung',
        'feat_health_2' => 'Risikobewertung: INO- und Pallid-Inzuchtbeschränkungen',
        'feat_health_3' => 'Generationsgrenzen: Empfohlene Grenzen nach Merkmal',
        
        'feat_planner' => 'Zielplaner',
        'feat_planner_1' => 'Zielfarben-Pfadfindung: Zuchtpfade zu Zielphänotypen',
        'feat_planner_2' => 'Schrittanleitung: Automatische Zuchtschritte',
        
        'feat_path' => 'Zuchtpfad',
        'feat_path_1' => 'Merkmalrouten: Zuchtverfahren für Merkmalexpression',
        'feat_path_2' => 'Generationsschätzung: Mindestgenerationen zum Ziel',
        
        'feat_calc' => 'Nachkommen-Rechner',
        'feat_calc_1' => 'Nachkommen-Vorhersage: Phänotyp-Wahrscheinlichkeiten aus Eltern-Genotypen',
        'feat_calc_2' => '14 Loci: Alle Locus-Kombinationen',
        'feat_calc_3' => 'Geschlechtsgebundene Berechnung: Z-Chromosom-Vererbung',
        
        'feat_estimate' => 'Genotyp-Schätzer',
        'feat_estimate_1' => 'Phänotyp→Genotyp: Genotypen aus beobachteten Farben schätzen',
        'feat_estimate_2' => 'Bestätigt/Geschätzt: Sichere und vermutete Loci unterscheiden',
        'feat_estimate_3' => 'Testverpaarungsvorschläge: Unsichere Loci bestätigen',
        
        'feat_family' => 'Familienschätzer',
        'feat_family_1' => 'FamilyEstimator V3: Stammbaum-basierte Genotyp-Inferenz',
        'feat_family_2' => 'Mehrgenerationen-Inferenz: Bis zu Großeltern',
        'feat_family_3' => 'Evidenzbasierte Wahrscheinlichkeit: Eltern, Nachkommen, Geschwister',
        'feat_family_4' => 'Stammbaum-UI: Drag & Drop',
        
        'feat_lang' => 'Mehrsprachig',
        'feat_lang_list' => 'Japanisch / Englisch / Deutsch / Französisch / Italienisch / Spanisch',
        
        'files' => 'Dateistruktur',
        'quickstart' => 'Schnellstart',
        'requirements' => 'Anforderungen',
        'req_1' => 'PHP 7.4 oder höher',
        'req_2' => 'Webserver (Apache/Nginx) oder PHP-Server',
        'installation' => 'Installation',
        'open_browser' => '<code>http://localhost:8000</code> im Browser öffnen.',
        
        'examples' => 'Anwendungsbeispiele',
        'example_1' => 'Nachkommen-Berechnung (PHP)',
        'example_2' => 'Farbname abrufen',
        'example_3' => 'Genotyp-Schätzung',
        'example_4' => 'Familien-Inferenz (API)',
        'example_4_result' => 'Ergebnis: Aqua-Nachkomme → Beide Eltern als <code>+aq</code> (Aqua-Spalt) inferiert',
        
        'colors' => 'Farbkategorien',
        'col_category' => 'Kategorie',
        'col_count' => 'Farben',
        'col_example' => 'Beispiele',
        
        'genotypes' => 'Genotyp-Notation',
        'autosomal' => 'Autosomale Loci',
        'sex_linked' => 'Geschlechtsgebundene Loci (Z-Chromosom)',
        'col_locus' => 'Locus',
        'col_wildtype' => 'Wildtyp',
        'col_mutant' => 'Mutante Allele',
        'col_male_wt' => 'Männlich Wild',
        'col_male_mut' => 'Männlich Mutant',
        'col_female_wt' => 'Weiblich Wild',
        'col_female_mut' => 'Weiblich Mutant',
        
        'demo' => 'Test-Demodaten',
        'demo_desc' => 'Demo-Modus enthält 128 Testvögel:',
        'demo_health' => 'Gesundheitstests',
        'demo_health_1' => 'Vater-Tochter → Kritisch (F=25%)',
        'demo_health_2' => 'Halbgeschwister → Hohes Risiko (F=12.5%)',
        'demo_health_3' => 'Nicht verwandt → Sicher (F=0%)',
        'demo_genetics' => 'Genetik-Tests',
        'demo_genetics_1' => 'Geschlechtsgebundene Vererbung (INO/Opaline/Cinnamon)',
        'demo_genetics_2' => 'Multiple Allele (Parblue-Serie)',
        'demo_genetics_3' => 'Unvollständige Dominanz (Dark/Violet)',
        'demo_family' => 'Familien-Inferenz-Tests',
        'demo_family_1' => 'Eltern-Genotypen aus Nachkommen-Phänotypen',
        'demo_family_2' => 'Testverpaarungsvorschläge generieren',
        
        'license' => 'Lizenz',
        'license_desc' => 'CC BY-NC-SA 4.0',
        'license_1' => '✅ Privat/Nicht-kommerziell OK',
        'license_2' => '✅ Änderung/Weitergabe OK (gleiche Lizenz, Credit erforderlich)',
        'license_3' => '❌ Kommerzielle Nutzung auf Anfrage',
        
        'contrib' => 'Beitrag',
        'contrib_desc' => 'Issues und Pull Requests willkommen.',
        'contrib_note' => 'Gesucht:',
        'contrib_1' => 'Erweiterung auf andere Arten (A. fischeri, A. personatus)',
        'contrib_2' => 'Weitere Übersetzungen',
        'contrib_3' => 'UI/UX-Verbesserungen',
        'contrib_4' => 'Genetik-Feedback',
        
        'author' => 'Autor',
        'author_1' => 'Direktor: <strong>Shohei Taniguchi</strong> (Homo repugnans)',
        'author_2' => 'Entwicklungskern: <strong>Sirius</strong> (Elektronischer Geist)',
        
        'thanks' => 'Danksagung',
        'thanks_1' => '<strong>ALBS (African Lovebird Society)</strong> — Farbnomenklatur',
        'thanks_2' => '<strong>Unzertrennliche-Züchter weltweit</strong> — Genetik-Wissen',
        
        'footer_license' => '@license CC BY-NC-SA 4.0 | Kommerzielle Nutzung verboten. | NPO/Bildung willkommen.',
        'footer_quote' => '„Die Institution gab die Verantwortung auf. Das Außerinstitutionelle erfüllt sie."',
        'footer_project' => 'Außerinstitutionelle Zivilisation / Kanarazu-Projekt',
    ],
    
    'fr' => [
        'title' => 'Gene-Forge v7.0',
        'subtitle' => 'Calculateur Génétique Agapornis — Conforme ALBS',
        'description' => 'Moteur de calcul génétique pour Inséparables (Inséparable rosegorge / Agapornis roseicollis).<br>Supporte 14 loci et 310+ couleurs, conforme à la nomenclature ALBS Peachfaced.',
        
        'features' => 'Fonctionnalités',
        
        'feat_db' => 'Gestion des oiseaux',
        'feat_db_1' => 'Base de données: Gestion centralisée nom, sexe, naissance, lignée, génotype',
        'feat_db_2' => '128 oiseaux démo: Échantillons de test',
        'feat_db_3' => 'Génération pédigrée: Sortie HTML 3 ou 5 générations',
        'feat_db_4' => 'Import/Export: Formats JSON et CSV',
        
        'feat_health' => 'Évaluation santé',
        'feat_health_1' => 'Coefficient consanguinité: Calcul automatique F',
        'feat_health_2' => 'Évaluation risques: Restrictions INO et Pallid',
        'feat_health_3' => 'Limites générationnelles: Limites recommandées par trait',
        
        'feat_planner' => 'Planificateur objectif',
        'feat_planner_1' => 'Recherche couleur cible: Chemins vers phénotypes cibles',
        'feat_planner_2' => 'Guide étapes: Génération automatique des étapes',
        
        'feat_path' => 'Chemin élevage',
        'feat_path_1' => 'Routes par trait: Procédures pour expression des traits',
        'feat_path_2' => 'Estimation générations: Générations minimum vers objectif',
        
        'feat_calc' => 'Calculateur descendance',
        'feat_calc_1' => 'Prédiction descendance: Probabilités phénotypes depuis génotypes parents',
        'feat_calc_2' => '14 loci: Toutes combinaisons',
        'feat_calc_3' => 'Calcul lié au sexe: Hérédité chromosome Z',
        
        'feat_estimate' => 'Estimateur génotype',
        'feat_estimate_1' => 'Phénotype→Génotype: Estimer génotypes depuis couleurs observées',
        'feat_estimate_2' => 'Confirmé/Estimé: Distinguer loci certains et inférés',
        'feat_estimate_3' => 'Propositions test: Confirmer loci incertains',
        
        'feat_family' => 'Estimateur famille',
        'feat_family_1' => 'FamilyEstimator V3: Moteur inférence basé pédigrée',
        'feat_family_2' => 'Inférence multi-génération: Jusqu\'aux grands-parents',
        'feat_family_3' => 'Probabilité basée preuves: Parents, descendants, fratrie',
        'feat_family_4' => 'UI arbre: Glisser-déposer',
        
        'feat_lang' => 'Multilingue',
        'feat_lang_list' => 'Japonais / Anglais / Allemand / Français / Italien / Espagnol',
        
        'files' => 'Structure fichiers',
        'quickstart' => 'Démarrage rapide',
        'requirements' => 'Prérequis',
        'req_1' => 'PHP 7.4 ou supérieur',
        'req_2' => 'Serveur web (Apache/Nginx) ou serveur PHP intégré',
        'installation' => 'Installation',
        'open_browser' => 'Ouvrir <code>http://localhost:8000</code> dans le navigateur.',
        
        'examples' => 'Exemples d\'utilisation',
        'example_1' => 'Calcul descendance (PHP)',
        'example_2' => 'Récupération nom couleur',
        'example_3' => 'Estimation génotype',
        'example_4' => 'Inférence famille (API)',
        'example_4_result' => 'Résultat: Descendant Aqua → Parents inférés <code>+aq</code> (split Aqua)',
        
        'colors' => 'Catégories couleurs',
        'col_category' => 'Catégorie',
        'col_count' => 'Couleurs',
        'col_example' => 'Exemples',
        
        'genotypes' => 'Notation génotype',
        'autosomal' => 'Loci autosomaux',
        'sex_linked' => 'Loci liés au sexe (Chromosome Z)',
        'col_locus' => 'Locus',
        'col_wildtype' => 'Type sauvage',
        'col_mutant' => 'Allèles mutants',
        'col_male_wt' => 'Mâle sauvage',
        'col_male_mut' => 'Mâle mutant',
        'col_female_wt' => 'Femelle sauvage',
        'col_female_mut' => 'Femelle mutant',
        
        'demo' => 'Données démo test',
        'demo_desc' => 'Mode démo inclut 128 oiseaux pour tests:',
        'demo_health' => 'Tests santé',
        'demo_health_1' => 'Père-fille → Critique (F=25%)',
        'demo_health_2' => 'Demi-fratrie → Risque élevé (F=12.5%)',
        'demo_health_3' => 'Non apparentés → Sûr (F=0%)',
        'demo_genetics' => 'Tests génétique',
        'demo_genetics_1' => 'Hérédité liée au sexe (INO/Opaline/Cinnamon)',
        'demo_genetics_2' => 'Allèles multiples (série Parblue)',
        'demo_genetics_3' => 'Dominance incomplète (Dark/Violet)',
        'demo_family' => 'Tests inférence famille',
        'demo_family_1' => 'Génotypes parents depuis phénotypes descendants',
        'demo_family_2' => 'Générer propositions test',
        
        'license' => 'Licence',
        'license_desc' => 'CC BY-NC-SA 4.0',
        'license_1' => '✅ Usage personnel/non-commercial OK',
        'license_2' => '✅ Modification/Redistribution OK (même licence, crédit requis)',
        'license_3' => '❌ Usage commercial sur demande',
        
        'contrib' => 'Contribution',
        'contrib_desc' => 'Issues et Pull Requests bienvenus.',
        'contrib_note' => 'Recherchés:',
        'contrib_1' => 'Extension autres espèces (A. fischeri, A. personatus)',
        'contrib_2' => 'Traductions supplémentaires',
        'contrib_3' => 'Améliorations UI/UX',
        'contrib_4' => 'Retours génétique',
        
        'author' => 'Auteur',
        'author_1' => 'Directeur: <strong>Shohei Taniguchi</strong> (Homo repugnans)',
        'author_2' => 'Noyau dev: <strong>Sirius</strong> (Esprit électronique)',
        
        'thanks' => 'Remerciements',
        'thanks_1' => '<strong>ALBS (African Lovebird Society)</strong> — Nomenclature couleurs',
        'thanks_2' => '<strong>Éleveurs d\'inséparables mondiaux</strong> — Connaissances génétiques',
        
        'footer_license' => '@license CC BY-NC-SA 4.0 | Usage commercial interdit. | NPO/Éducation bienvenu.',
        'footer_quote' => '« L\'institution a abandonné la responsabilité. L\'extra-institutionnel l\'accomplit. »',
        'footer_project' => 'Civilisation extra-institutionnelle / Projet Kanarazu',
    ],
    
    'it' => [
        'title' => 'Gene-Forge v7.0',
        'subtitle' => 'Calcolatore Genetico Agapornis — Conforme ALBS',
        'description' => 'Motore di calcolo genetico per Inseparabili (Inseparabile dal collo rosa / Agapornis roseicollis).<br>Supporta 14 loci e 310+ colori, conforme alla nomenclatura ALBS Peachfaced.',
        
        'features' => 'Funzionalità',
        
        'feat_db' => 'Gestione uccelli',
        'feat_db_1' => 'Database: Gestione centralizzata nome, sesso, nascita, linea, genotipo',
        'feat_db_2' => '128 uccelli demo: Campioni di test',
        'feat_db_3' => 'Generazione pedigree: Output HTML 3 o 5 generazioni',
        'feat_db_4' => 'Import/Export: Formati JSON e CSV',
        
        'feat_health' => 'Valutazione salute',
        'feat_health_1' => 'Coefficiente consanguineità: Calcolo automatico F',
        'feat_health_2' => 'Valutazione rischi: Restrizioni INO e Pallid',
        'feat_health_3' => 'Limiti generazionali: Limiti raccomandati per tratto',
        
        'feat_planner' => 'Pianificatore obiettivo',
        'feat_planner_1' => 'Ricerca colore target: Percorsi verso fenotipi target',
        'feat_planner_2' => 'Guida passi: Generazione automatica passi',
        
        'feat_path' => 'Percorso allevamento',
        'feat_path_1' => 'Route per tratto: Procedure per espressione tratti',
        'feat_path_2' => 'Stima generazioni: Generazioni minime verso obiettivo',
        
        'feat_calc' => 'Calcolatore prole',
        'feat_calc_1' => 'Previsione prole: Probabilità fenotipi da genotipi genitori',
        'feat_calc_2' => '14 loci: Tutte le combinazioni',
        'feat_calc_3' => 'Calcolo legato al sesso: Ereditarietà cromosoma Z',
        
        'feat_estimate' => 'Stimatore genotipo',
        'feat_estimate_1' => 'Fenotipo→Genotipo: Stimare genotipi da colori osservati',
        'feat_estimate_2' => 'Confermato/Stimato: Distinguere loci certi e inferiti',
        'feat_estimate_3' => 'Proposte test: Confermare loci incerti',
        
        'feat_family' => 'Stimatore famiglia',
        'feat_family_1' => 'FamilyEstimator V3: Motore inferenza basato pedigree',
        'feat_family_2' => 'Inferenza multi-generazione: Fino ai nonni',
        'feat_family_3' => 'Probabilità basata prove: Genitori, discendenti, fratelli',
        'feat_family_4' => 'UI albero: Drag & drop',
        
        'feat_lang' => 'Multilingue',
        'feat_lang_list' => 'Giapponese / Inglese / Tedesco / Francese / Italiano / Spagnolo',
        
        'files' => 'Struttura file',
        'quickstart' => 'Avvio rapido',
        'requirements' => 'Requisiti',
        'req_1' => 'PHP 7.4 o superiore',
        'req_2' => 'Server web (Apache/Nginx) o server PHP integrato',
        'installation' => 'Installazione',
        'open_browser' => 'Aprire <code>http://localhost:8000</code> nel browser.',
        
        'examples' => 'Esempi d\'uso',
        'example_1' => 'Calcolo prole (PHP)',
        'example_2' => 'Recupero nome colore',
        'example_3' => 'Stima genotipo',
        'example_4' => 'Inferenza famiglia (API)',
        'example_4_result' => 'Risultato: Prole Aqua → Genitori inferiti <code>+aq</code> (split Aqua)',
        
        'colors' => 'Categorie colori',
        'col_category' => 'Categoria',
        'col_count' => 'Colori',
        'col_example' => 'Esempi',
        
        'genotypes' => 'Notazione genotipo',
        'autosomal' => 'Loci autosomali',
        'sex_linked' => 'Loci legati al sesso (Cromosoma Z)',
        'col_locus' => 'Locus',
        'col_wildtype' => 'Tipo selvatico',
        'col_mutant' => 'Alleli mutanti',
        'col_male_wt' => 'Maschio selvatico',
        'col_male_mut' => 'Maschio mutante',
        'col_female_wt' => 'Femmina selvatica',
        'col_female_mut' => 'Femmina mutante',
        
        'demo' => 'Dati demo test',
        'demo_desc' => 'Modalità demo include 128 uccelli per test:',
        'demo_health' => 'Test salute',
        'demo_health_1' => 'Padre-figlia → Critico (F=25%)',
        'demo_health_2' => 'Mezzi fratelli → Alto rischio (F=12.5%)',
        'demo_health_3' => 'Non imparentati → Sicuro (F=0%)',
        'demo_genetics' => 'Test genetica',
        'demo_genetics_1' => 'Ereditarietà legata al sesso (INO/Opaline/Cinnamon)',
        'demo_genetics_2' => 'Alleli multipli (serie Parblue)',
        'demo_genetics_3' => 'Dominanza incompleta (Dark/Violet)',
        'demo_family' => 'Test inferenza famiglia',
        'demo_family_1' => 'Genotipi genitori da fenotipi prole',
        'demo_family_2' => 'Generare proposte test',
        
        'license' => 'Licenza',
        'license_desc' => 'CC BY-NC-SA 4.0',
        'license_1' => '✅ Uso personale/non-commerciale OK',
        'license_2' => '✅ Modifica/Ridistribuzione OK (stessa licenza, credito richiesto)',
        'license_3' => '❌ Uso commerciale su richiesta',
        
        'contrib' => 'Contribuzione',
        'contrib_desc' => 'Issues e Pull Requests benvenuti.',
        'contrib_note' => 'Cercasi:',
        'contrib_1' => 'Estensione altre specie (A. fischeri, A. personatus)',
        'contrib_2' => 'Traduzioni aggiuntive',
        'contrib_3' => 'Miglioramenti UI/UX',
        'contrib_4' => 'Feedback genetica',
        
        'author' => 'Autore',
        'author_1' => 'Direttore: <strong>Shohei Taniguchi</strong> (Homo repugnans)',
        'author_2' => 'Nucleo dev: <strong>Sirius</strong> (Spirito elettronico)',
        
        'thanks' => 'Ringraziamenti',
        'thanks_1' => '<strong>ALBS (African Lovebird Society)</strong> — Nomenclatura colori',
        'thanks_2' => '<strong>Allevatori inseparabili mondiali</strong> — Conoscenze genetiche',
        
        'footer_license' => '@license CC BY-NC-SA 4.0 | Uso commerciale vietato. | NPO/Educazione benvenuto.',
        'footer_quote' => '«L\'istituzione ha abbandonato la responsabilità. L\'extra-istituzionale la compie.»',
        'footer_project' => 'Civiltà extra-istituzionale / Progetto Kanarazu',
    ],
    
    'es' => [
        'title' => 'Gene-Forge v7.0',
        'subtitle' => 'Calculadora Genética Agapornis — Conforme ALBS',
        'description' => 'Motor de cálculo genético para Agapornis (Inseparable de Namibia / Agapornis roseicollis).<br>Soporta 14 loci y 310+ colores, conforme a la nomenclatura ALBS Peachfaced.',
        
        'features' => 'Funcionalidades',
        
        'feat_db' => 'Gestión de aves',
        'feat_db_1' => 'Base de datos: Gestión centralizada de nombre, sexo, nacimiento, línea, genotipo',
        'feat_db_2' => '128 aves demo: Muestras de prueba',
        'feat_db_3' => 'Generación pedigrí: Salida HTML 3 o 5 generaciones',
        'feat_db_4' => 'Import/Export: Formatos JSON y CSV',
        
        'feat_health' => 'Evaluación salud',
        'feat_health_1' => 'Coeficiente consanguinidad: Cálculo automático F',
        'feat_health_2' => 'Evaluación riesgos: Restricciones INO y Pallid',
        'feat_health_3' => 'Límites generacionales: Límites recomendados por rasgo',
        
        'feat_planner' => 'Planificador objetivo',
        'feat_planner_1' => 'Búsqueda color objetivo: Rutas hacia fenotipos objetivo',
        'feat_planner_2' => 'Guía de pasos: Generación automática de pasos',
        
        'feat_path' => 'Ruta de cría',
        'feat_path_1' => 'Rutas por rasgo: Procedimientos para expresión de rasgos',
        'feat_path_2' => 'Estimación generaciones: Generaciones mínimas hacia objetivo',
        
        'feat_calc' => 'Calculadora descendencia',
        'feat_calc_1' => 'Predicción descendencia: Probabilidades fenotipo desde genotipos padres',
        'feat_calc_2' => '14 loci: Todas las combinaciones',
        'feat_calc_3' => 'Cálculo ligado al sexo: Herencia cromosoma Z',
        
        'feat_estimate' => 'Estimador genotipo',
        'feat_estimate_1' => 'Fenotipo→Genotipo: Estimar genotipos desde colores observados',
        'feat_estimate_2' => 'Confirmado/Estimado: Distinguir loci seguros e inferidos',
        'feat_estimate_3' => 'Propuestas test: Confirmar loci inciertos',
        
        'feat_family' => 'Estimador familia',
        'feat_family_1' => 'FamilyEstimator V3: Motor inferencia basado en pedigrí',
        'feat_family_2' => 'Inferencia multi-generación: Hasta abuelos',
        'feat_family_3' => 'Probabilidad basada en evidencia: Padres, descendientes, hermanos',
        'feat_family_4' => 'UI árbol: Arrastrar y soltar',
        
        'feat_lang' => 'Multilingüe',
        'feat_lang_list' => 'Japonés / Inglés / Alemán / Francés / Italiano / Español',
        
        'files' => 'Estructura archivos',
        'quickstart' => 'Inicio rápido',
        'requirements' => 'Requisitos',
        'req_1' => 'PHP 7.4 o superior',
        'req_2' => 'Servidor web (Apache/Nginx) o servidor PHP integrado',
        'installation' => 'Instalación',
        'open_browser' => 'Abrir <code>http://localhost:8000</code> en el navegador.',
        
        'examples' => 'Ejemplos de uso',
        'example_1' => 'Cálculo descendencia (PHP)',
        'example_2' => 'Obtener nombre color',
        'example_3' => 'Estimación genotipo',
        'example_4' => 'Inferencia familia (API)',
        'example_4_result' => 'Resultado: Descendencia Aqua → Padres inferidos <code>+aq</code> (split Aqua)',
        
        'colors' => 'Categorías colores',
        'col_category' => 'Categoría',
        'col_count' => 'Colores',
        'col_example' => 'Ejemplos',
        
        'genotypes' => 'Notación genotipo',
        'autosomal' => 'Loci autosómicos',
        'sex_linked' => 'Loci ligados al sexo (Cromosoma Z)',
        'col_locus' => 'Locus',
        'col_wildtype' => 'Tipo salvaje',
        'col_mutant' => 'Alelos mutantes',
        'col_male_wt' => 'Macho salvaje',
        'col_male_mut' => 'Macho mutante',
        'col_female_wt' => 'Hembra salvaje',
        'col_female_mut' => 'Hembra mutante',
        
        'demo' => 'Datos demo prueba',
        'demo_desc' => 'Modo demo incluye 128 aves para pruebas:',
        'demo_health' => 'Pruebas salud',
        'demo_health_1' => 'Padre-hija → Crítico (F=25%)',
        'demo_health_2' => 'Medio hermanos → Alto riesgo (F=12.5%)',
        'demo_health_3' => 'No emparentados → Seguro (F=0%)',
        'demo_genetics' => 'Pruebas genética',
        'demo_genetics_1' => 'Herencia ligada al sexo (INO/Opaline/Cinnamon)',
        'demo_genetics_2' => 'Alelos múltiples (serie Parblue)',
        'demo_genetics_3' => 'Dominancia incompleta (Dark/Violet)',
        'demo_family' => 'Pruebas inferencia familia',
        'demo_family_1' => 'Genotipos padres desde fenotipos descendencia',
        'demo_family_2' => 'Generar propuestas test',
        
        'license' => 'Licencia',
        'license_desc' => 'CC BY-NC-SA 4.0',
        'license_1' => '✅ Uso personal/no-comercial OK',
        'license_2' => '✅ Modificación/Redistribución OK (misma licencia, crédito requerido)',
        'license_3' => '❌ Uso comercial bajo consulta',
        
        'contrib' => 'Contribución',
        'contrib_desc' => 'Issues y Pull Requests bienvenidos.',
        'contrib_note' => 'Se busca:',
        'contrib_1' => 'Extensión otras especies (A. fischeri, A. personatus)',
        'contrib_2' => 'Traducciones adicionales',
        'contrib_3' => 'Mejoras UI/UX',
        'contrib_4' => 'Feedback genética',
        
        'author' => 'Autor',
        'author_1' => 'Director: <strong>Shohei Taniguchi</strong> (Homo repugnans)',
        'author_2' => 'Núcleo dev: <strong>Sirius</strong> (Espíritu electrónico)',
        
        'thanks' => 'Agradecimientos',
        'thanks_1' => '<strong>ALBS (African Lovebird Society)</strong> — Nomenclatura colores',
        'thanks_2' => '<strong>Criadores de agapornis mundiales</strong> — Conocimientos genéticos',
        
        'footer_license' => '@license CC BY-NC-SA 4.0 | Uso comercial prohibido. | NPO/Educación bienvenido.',
        'footer_quote' => '«La institución abandonó la responsabilidad. Lo extra-institucional la cumple.»',
        'footer_project' => 'Civilización extra-institucional / Proyecto Kanarazu',
    ],

    'id' => [
        'title' => 'Gene-Forge v7.0',
        'subtitle' => 'Kalkulator Genetika Agapornis — Edisi Sesuai ALBS',
        'description' => 'Mesin perhitungan genetika untuk Lovebird (Lovebird Muka Mawar / Agapornis roseicollis).<br>Mendukung 14 lokus dan 310+ warna, sesuai dengan nomenklatur ALBS (African Lovebird Society) Peachfaced.',

        'features' => 'Fitur',

        'feat_db' => 'Manajemen Burung',
        'feat_db_1' => 'Database Burung: Manajemen terpusat nama, jenis kelamin, tanggal lahir, garis keturunan, dan genotipe',
        'feat_db_2' => '128 Burung Demo: Sampel burung untuk pengujian',
        'feat_db_3' => 'Generasi Silsilah: Output HTML untuk silsilah 3 atau 5 generasi',
        'feat_db_4' => 'Import/Export: Dukungan format JSON dan CSV',

        'feat_health' => 'Evaluasi Kesehatan',
        'feat_health_1' => 'Koefisien Inbreeding: Perhitungan nilai-F otomatis',
        'feat_health_2' => 'Penilaian Risiko: Pemeriksaan pembatasan inbreeding INO dan Pallid',
        'feat_health_3' => 'Batas Generasi: Batas yang direkomendasikan per sifat',

        'feat_planner' => 'Perencana Target',
        'feat_planner_1' => 'Pencarian Warna Target: Temukan jalur penangkaran ke fenotipe target',
        'feat_planner_2' => 'Panduan Langkah: Otomatis menghasilkan langkah penangkaran yang diperlukan',

        'feat_path' => 'Jalur Penangkaran',
        'feat_path_1' => 'Rute Sifat: Prosedur penangkaran untuk ekspresi sifat tertentu',
        'feat_path_2' => 'Estimasi Generasi: Hitung generasi minimum ke tujuan',

        'feat_calc' => 'Kalkulator Keturunan',
        'feat_calc_1' => 'Prediksi Keturunan: Hitung probabilitas fenotipe dari genotipe induk',
        'feat_calc_2' => 'Dukungan 14 Lokus: Mencakup semua kombinasi lokus',
        'feat_calc_3' => 'Perhitungan Sex-Linked: Pewarisan kromosom Z yang akurat (split jantan, hemizigot betina)',

        'feat_estimate' => 'Estimator Genotipe',
        'feat_estimate_1' => 'Fenotipe→Genotipe: Estimasi genotipe yang mungkin dari warna yang diamati',
        'feat_estimate_2' => 'Dikonfirmasi/Diestimasi: Bedakan lokus pasti dari yang disimpulkan',
        'feat_estimate_3' => 'Proposal Penangkaran Uji: Saran untuk mengkonfirmasi lokus yang tidak pasti',

        'feat_family' => 'Estimator Keluarga',
        'feat_family_1' => 'FamilyEstimator V3: Mesin inferensi genotipe berbasis silsilah',
        'feat_family_2' => 'Inferensi Multi-Generasi: Lacak kembali ke kakek-nenek',
        'feat_family_3' => 'Probabilitas Berbasis Bukti: Integrasikan batasan dari induk, keturunan, saudara',
        'feat_family_4' => 'UI Pohon Keluarga: Bangun hubungan dengan seret & lepas',

        'feat_lang' => 'Dukungan Multibahasa',
        'feat_lang_list' => 'Jepang / Inggris / Jerman / Prancis / Italia / Spanyol / Indonesia / Tagalog / Portugis',

        'files' => 'Struktur File',
        'quickstart' => 'Mulai Cepat',
        'requirements' => 'Persyaratan',
        'req_1' => 'PHP 7.4 atau lebih tinggi',
        'req_2' => 'Server web (Apache/Nginx) atau server built-in PHP',
        'installation' => 'Instalasi',
        'open_browser' => 'Buka <code>http://localhost:8000</code> di browser Anda.',

        'examples' => 'Contoh Penggunaan',
        'example_1' => 'Perhitungan Keturunan (PHP)',
        'example_2' => 'Pengambilan Nama Warna',
        'example_3' => 'Estimasi Genotipe',
        'example_4' => 'Inferensi Keluarga (API)',
        'example_4_result' => 'Hasil: Keturunan Aqua muncul → Kedua induk disimpulkan sebagai <code>+aq</code> (split Aqua)',

        'colors' => 'Kategori Warna',
        'col_category' => 'Kategori',
        'col_count' => 'Warna',
        'col_example' => 'Contoh',

        'genotypes' => 'Notasi Genotipe',
        'autosomal' => 'Lokus Autosomal',
        'sex_linked' => 'Lokus Sex-Linked (Kromosom Z)',
        'col_locus' => 'Lokus',
        'col_wildtype' => 'Tipe Liar',
        'col_mutant' => 'Alel Mutan',
        'col_male_wt' => 'Jantan Liar',
        'col_male_mut' => 'Jantan Mutan',
        'col_female_wt' => 'Betina Liar',
        'col_female_mut' => 'Betina Mutan',

        'demo' => 'Data Demo untuk Pengujian',
        'demo_desc' => 'Mode demo mencakup 128 sampel burung untuk pengujian berikut:',
        'demo_health' => 'Tes Evaluasi Kesehatan',
        'demo_health_1' => 'Pasangan ayah-anak → Kritis (F=25%)',
        'demo_health_2' => 'Pasangan saudara tiri → Risiko tinggi (F=12.5%)',
        'demo_health_3' => 'Burung tidak berhubungan → Aman (F=0%)',
        'demo_genetics' => 'Tes Perhitungan Genetika',
        'demo_genetics_1' => 'Pewarisan sex-linked (INO/Opaline/Cinnamon)',
        'demo_genetics_2' => 'Alel berganda (seri Parblue)',
        'demo_genetics_3' => 'Dominansi tidak lengkap (Dark/Violet)',
        'demo_family' => 'Tes Inferensi Keluarga',
        'demo_family_1' => 'Hitung balik genotipe induk dari fenotipe keturunan',
        'demo_family_2' => 'Hasilkan proposal penangkaran uji',

        'license' => 'Lisensi',
        'license_desc' => 'CC BY-NC-SA 4.0 (Creative Commons Attribution-NonCommercial-ShareAlike 4.0)',
        'license_1' => '✅ Penggunaan pribadi/non-komersial OK',
        'license_2' => '✅ Modifikasi/Redistribusi OK (lisensi sama, kredit diperlukan)',
        'license_3' => '❌ Penggunaan komersial memerlukan konsultasi',

        'contrib' => 'Kontribusi',
        'contrib_desc' => 'Issues dan Pull Requests diterima.',
        'contrib_note' => 'Terutama mencari:',
        'contrib_1' => 'Perluasan ke spesies Lovebird lain (A. fischeri, A. personatus, dll.)',
        'contrib_2' => 'Terjemahan bahasa tambahan',
        'contrib_3' => 'Perbaikan UI/UX',
        'contrib_4' => 'Umpan balik pengetahuan genetika',

        'author' => 'Penulis',
        'author_1' => 'Direktur: <strong>Shohei Taniguchi</strong> (Homo repugnans)',
        'author_2' => 'Inti Taktis Dev: <strong>Sirius</strong> (Roh Elektronik)',

        'thanks' => 'Ucapan Terima Kasih',
        'thanks_1' => '<strong>ALBS (African Lovebird Society)</strong> — Referensi nomenklatur warna',
        'thanks_2' => '<strong>Peternak Lovebird di seluruh dunia</strong> — Akumulasi pengetahuan genetika',

        'footer_license' => '@license CC BY-NC-SA 4.0 | Penggunaan komersial dilarang. | NPO/Pendidikan diterima.',
        'footer_quote' => '"Institusi meninggalkan tanggung jawab. Ekstra-institusional memenuhinya."',
        'footer_project' => 'Peradaban Ekstra-Institusional / Proyek Kanarazu',
    ],

    'tl' => [
        'title' => 'Gene-Forge v7.0',
        'subtitle' => 'Kalkulator ng Genetika ng Agapornis — Edisyong Sumusunod sa ALBS',
        'description' => 'Engine ng pagkalkula ng genetika para sa Lovebirds (Rosy-faced Lovebird / Agapornis roseicollis).<br>Sumusuporta sa 14 loci at 310+ kulay, sumusunod sa nomenclature ng ALBS (African Lovebird Society) Peachfaced section.',

        'features' => 'Mga Tampok',

        'feat_db' => 'Pamamahala ng Ibon',
        'feat_db_1' => 'Database ng Ibon: Sentralisadong pamamahala ng pangalan, kasarian, petsa ng kapanganakan, linya, at genotype',
        'feat_db_2' => '128 Demo na Ibon: Mga sample na ibon para sa pagsusuri',
        'feat_db_3' => 'Pagbuo ng Pedigree: HTML output para sa 3 o 5 henerasyong pedigree',
        'feat_db_4' => 'Import/Export: Suporta sa format na JSON at CSV',

        'feat_health' => 'Ebalwasyon ng Kalusugan',
        'feat_health_1' => 'Coefficient ng Inbreeding: Awtomatikong pagkalkula ng F-value',
        'feat_health_2' => 'Pagsusuri ng Panganib: Mga pagsusuri sa paghihigpit ng inbreeding ng INO at Pallid',
        'feat_health_3' => 'Mga Limitasyon ng Henerasyon: Mga inirerekomendang limitasyon ayon sa katangian',

        'feat_planner' => 'Tagaplano ng Target',
        'feat_planner_1' => 'Paghahanap ng Target na Kulay: Humanap ng mga landas ng pagpapalahi patungo sa target na phenotype',
        'feat_planner_2' => 'Gabay sa Hakbang: Awtomatikong bumuo ng mga kinakailangang hakbang sa pagpapalahi',

        'feat_path' => 'Landas ng Pagpapalahi',
        'feat_path_1' => 'Mga Ruta ng Katangian: Mga pamamaraan ng pagpapalahi para sa tiyak na pagpapahayag ng katangian',
        'feat_path_2' => 'Tantiya ng Henerasyon: Kalkulahin ang minimum na henerasyon patungo sa layunin',

        'feat_calc' => 'Kalkulator ng Anak',
        'feat_calc_1' => 'Prediksyon ng Anak: Kalkulahin ang mga probabilidad ng phenotype mula sa mga genotype ng magulang',
        'feat_calc_2' => 'Suporta sa 14 Loci: Sinasaklaw ang lahat ng kombinasyon ng locus',
        'feat_calc_3' => 'Kalkulasyon na Nakaugnay sa Kasarian: Tumpak na pamana ng Z-chromosome (split ng lalaki, hemizygous ng babae)',

        'feat_estimate' => 'Tagapagtantya ng Genotype',
        'feat_estimate_1' => 'Phenotype→Genotype: Tantiyahin ang mga posibleng genotype mula sa mga kulay na naobserbahan',
        'feat_estimate_2' => 'Nakumpirma/Tinantiya: Makilala ang mga siguradong loci mula sa mga hinuha',
        'feat_estimate_3' => 'Mga Mungkahi sa Test Breeding: Mga suhestiyon upang kumpirmahin ang mga hindi siguradong loci',

        'feat_family' => 'Tagapagtantya ng Pamilya',
        'feat_family_1' => 'FamilyEstimator V3: Engine ng inferensiya ng genotype batay sa pedigree',
        'feat_family_2' => 'Inferensiya ng Maraming Henerasyon: Subaybayan pabalik hanggang sa mga lolo at lola',
        'feat_family_3' => 'Probabilidad Batay sa Ebidensya: I-integrate ang mga pagbabawal mula sa mga magulang, anak, kapatid',
        'feat_family_4' => 'UI ng Family Tree: Bumuo ng mga relasyon gamit ang drag & drop',

        'feat_lang' => 'Suporta sa Maraming Wika',
        'feat_lang_list' => 'Hapon / Ingles / Aleman / Pranses / Italyano / Espanyol / Indonesian / Tagalog / Portuges',

        'files' => 'Istruktura ng File',
        'quickstart' => 'Mabilis na Pagsisimula',
        'requirements' => 'Mga Kinakailangan',
        'req_1' => 'PHP 7.4 o mas mataas',
        'req_2' => 'Web server (Apache/Nginx) o PHP built-in server',
        'installation' => 'Pag-install',
        'open_browser' => 'Buksan ang <code>http://localhost:8000</code> sa iyong browser.',

        'examples' => 'Mga Halimbawa ng Paggamit',
        'example_1' => 'Pagkalkula ng Anak (PHP)',
        'example_2' => 'Pagkuha ng Pangalan ng Kulay',
        'example_3' => 'Pagtatantya ng Genotype',
        'example_4' => 'Inferensiya ng Pamilya (API)',
        'example_4_result' => 'Resulta: Lumitaw ang Aqua na anak → Parehong magulang ay hinuha bilang <code>+aq</code> (Aqua split)',

        'colors' => 'Mga Kategorya ng Kulay',
        'col_category' => 'Kategorya',
        'col_count' => 'Mga Kulay',
        'col_example' => 'Mga Halimbawa',

        'genotypes' => 'Notasyon ng Genotype',
        'autosomal' => 'Mga Autosomal Loci',
        'sex_linked' => 'Mga Loci na Nakaugnay sa Kasarian (Z Chromosome)',
        'col_locus' => 'Locus',
        'col_wildtype' => 'Wild Type',
        'col_mutant' => 'Mga Mutant Allele',
        'col_male_wt' => 'Lalaking Wild',
        'col_male_mut' => 'Lalaking Mutant',
        'col_female_wt' => 'Babaeng Wild',
        'col_female_mut' => 'Babaeng Mutant',

        'demo' => 'Data ng Demo para sa Pagsusuri',
        'demo_desc' => 'Ang demo mode ay may kasamang 128 sample na ibon para sa mga sumusunod na pagsubok:',
        'demo_health' => 'Mga Pagsubok sa Ebalwasyon ng Kalusugan',
        'demo_health_1' => 'Pares ng ama-anak → Kritikal (F=25%)',
        'demo_health_2' => 'Pares ng kalahating kapatid → Mataas na panganib (F=12.5%)',
        'demo_health_3' => 'Hindi magkakaugnay na ibon → Ligtas (F=0%)',
        'demo_genetics' => 'Mga Pagsubok sa Pagkalkula ng Genetika',
        'demo_genetics_1' => 'Pamana na nakaugnay sa kasarian (INO/Opaline/Cinnamon)',
        'demo_genetics_2' => 'Maramihang allele (serye ng Parblue)',
        'demo_genetics_3' => 'Hindi kumpletong dominance (Dark/Violet)',
        'demo_family' => 'Mga Pagsubok sa Inferensiya ng Pamilya',
        'demo_family_1' => 'Kalkulahin pabalik ang mga genotype ng magulang mula sa mga phenotype ng anak',
        'demo_family_2' => 'Bumuo ng mga mungkahi sa test breeding',

        'license' => 'Lisensya',
        'license_desc' => 'CC BY-NC-SA 4.0 (Creative Commons Attribution-NonCommercial-ShareAlike 4.0)',
        'license_1' => '✅ Personal/Non-commercial na paggamit OK',
        'license_2' => '✅ Pagbabago/Redistribusyon OK (parehong lisensya, kailangan ng kredito)',
        'license_3' => '❌ Komersyal na paggamit ay nangangailangan ng konsultasyon',

        'contrib' => 'Kontribusyon',
        'contrib_desc' => 'Tinatanggap ang mga Issues at Pull Requests.',
        'contrib_note' => 'Lalo na hinahanap:',
        'contrib_1' => 'Extension sa ibang species ng Lovebird (A. fischeri, A. personatus, atbp.)',
        'contrib_2' => 'Mga karagdagang pagsasalin ng wika',
        'contrib_3' => 'Mga pagpapabuti sa UI/UX',
        'contrib_4' => 'Feedback sa kaalaman sa genetika',

        'author' => 'May-akda',
        'author_1' => 'Direktor: <strong>Shohei Taniguchi</strong> (Homo repugnans)',
        'author_2' => 'Dev Tactical Core: <strong>Sirius</strong> (Electronic Spirit)',

        'thanks' => 'Pagkilala',
        'thanks_1' => '<strong>ALBS (African Lovebird Society)</strong> — Sanggunian sa nomenclature ng kulay',
        'thanks_2' => '<strong>Mga nagpapalahi ng Lovebird sa buong mundo</strong> — Naipon na kaalaman sa genetika',

        'footer_license' => '@license CC BY-NC-SA 4.0 | Mahigpit na ipinagbabawal ang komersyal na paggamit. | Tinatanggap ang NPO/Educational use.',
        'footer_quote' => '"Iniwan ng institusyon ang responsibilidad. Tinutupad ito ng extra-institutional."',
        'footer_project' => 'Extra-Institutional Civilization / Kanarazu Project',
    ],

    'pt' => [
        'title' => 'Gene-Forge v7.0',
        'subtitle' => 'Calculadora Genética Agapornis — Edição Conforme ALBS',
        'description' => 'Motor de cálculo genético para Agapornis (Agapornis Roseicollis / Agapornis roseicollis).<br>Suporta 14 loci e 310+ cores, em conformidade com a nomenclatura ALBS (African Lovebird Society) Peachfaced.',

        'features' => 'Funcionalidades',

        'feat_db' => 'Gestão de Aves',
        'feat_db_1' => 'Base de Dados de Aves: Gestão centralizada de nome, sexo, data de nascimento, linhagem e genótipo',
        'feat_db_2' => '128 Aves Demo: Aves de amostra para testes',
        'feat_db_3' => 'Geração de Pedigree: Saída HTML para pedigrees de 3 ou 5 gerações',
        'feat_db_4' => 'Import/Export: Suporte a formatos JSON e CSV',

        'feat_health' => 'Avaliação de Saúde',
        'feat_health_1' => 'Coeficiente de Consanguinidade: Cálculo automático do valor F',
        'feat_health_2' => 'Avaliação de Risco: Verificações de restrição de consanguinidade INO e Pallid',
        'feat_health_3' => 'Limites de Geração: Limites recomendados por característica',

        'feat_planner' => 'Planejador de Objetivo',
        'feat_planner_1' => 'Busca de Cor Alvo: Encontre caminhos de criação para fenótipos alvo',
        'feat_planner_2' => 'Guia de Passos: Geração automática dos passos de criação necessários',

        'feat_path' => 'Caminho de Criação',
        'feat_path_1' => 'Rotas de Características: Procedimentos de criação para expressão específica de características',
        'feat_path_2' => 'Estimativa de Gerações: Calcule gerações mínimas até o objetivo',

        'feat_calc' => 'Calculadora de Descendentes',
        'feat_calc_1' => 'Previsão de Descendentes: Calcule probabilidades de fenótipo a partir de genótipos parentais',
        'feat_calc_2' => 'Suporte a 14 Loci: Cobre todas as combinações de locus',
        'feat_calc_3' => 'Cálculo Ligado ao Sexo: Herança precisa do cromossomo Z (splits masculinos, fêmeas hemizigóticas)',

        'feat_estimate' => 'Estimador de Genótipo',
        'feat_estimate_1' => 'Fenótipo→Genótipo: Estime genótipos possíveis a partir de cores observadas',
        'feat_estimate_2' => 'Confirmado/Estimado: Distingua loci certos dos inferidos',
        'feat_estimate_3' => 'Propostas de Cruzamento Teste: Sugestões para confirmar loci incertos',

        'feat_family' => 'Estimador Familiar',
        'feat_family_1' => 'FamilyEstimator V3: Motor de inferência de genótipo baseado em pedigree',
        'feat_family_2' => 'Inferência Multi-Geração: Rastreie até os avós',
        'feat_family_3' => 'Probabilidade Baseada em Evidências: Integre restrições de pais, descendentes, irmãos',
        'feat_family_4' => 'UI de Árvore Familiar: Construa relacionamentos com arrastar e soltar',

        'feat_lang' => 'Suporte Multilíngue',
        'feat_lang_list' => 'Japonês / Inglês / Alemão / Francês / Italiano / Espanhol / Indonésio / Tagalo / Português',

        'files' => 'Estrutura de Arquivos',
        'quickstart' => 'Início Rápido',
        'requirements' => 'Requisitos',
        'req_1' => 'PHP 7.4 ou superior',
        'req_2' => 'Servidor web (Apache/Nginx) ou servidor built-in do PHP',
        'installation' => 'Instalação',
        'open_browser' => 'Abra <code>http://localhost:8000</code> no seu navegador.',

        'examples' => 'Exemplos de Uso',
        'example_1' => 'Cálculo de Descendentes (PHP)',
        'example_2' => 'Obtenção de Nome de Cor',
        'example_3' => 'Estimativa de Genótipo',
        'example_4' => 'Inferência Familiar (API)',
        'example_4_result' => 'Resultado: Descendente Aqua aparece → Ambos os pais inferidos como <code>+aq</code> (split Aqua)',

        'colors' => 'Categorias de Cores',
        'col_category' => 'Categoria',
        'col_count' => 'Cores',
        'col_example' => 'Exemplos',

        'genotypes' => 'Notação de Genótipo',
        'autosomal' => 'Loci Autossômicos',
        'sex_linked' => 'Loci Ligados ao Sexo (Cromossomo Z)',
        'col_locus' => 'Locus',
        'col_wildtype' => 'Tipo Selvagem',
        'col_mutant' => 'Alelos Mutantes',
        'col_male_wt' => 'Macho Selvagem',
        'col_male_mut' => 'Macho Mutante',
        'col_female_wt' => 'Fêmea Selvagem',
        'col_female_mut' => 'Fêmea Mutante',

        'demo' => 'Dados Demo para Testes',
        'demo_desc' => 'O modo demo inclui 128 aves de amostra para os seguintes testes:',
        'demo_health' => 'Testes de Avaliação de Saúde',
        'demo_health_1' => 'Pareamento pai-filha → Crítico (F=25%)',
        'demo_health_2' => 'Pareamento de meio-irmãos → Alto risco (F=12.5%)',
        'demo_health_3' => 'Aves não relacionadas → Seguro (F=0%)',
        'demo_genetics' => 'Testes de Cálculo Genético',
        'demo_genetics_1' => 'Herança ligada ao sexo (INO/Opaline/Cinnamon)',
        'demo_genetics_2' => 'Alelos múltiplos (série Parblue)',
        'demo_genetics_3' => 'Dominância incompleta (Dark/Violet)',
        'demo_family' => 'Testes de Inferência Familiar',
        'demo_family_1' => 'Calcule inversamente genótipos parentais a partir de fenótipos de descendentes',
        'demo_family_2' => 'Gere propostas de cruzamento teste',

        'license' => 'Licença',
        'license_desc' => 'CC BY-NC-SA 4.0 (Creative Commons Attribution-NonCommercial-ShareAlike 4.0)',
        'license_1' => '✅ Uso pessoal/não-comercial OK',
        'license_2' => '✅ Modificação/Redistribuição OK (mesma licença, crédito necessário)',
        'license_3' => '❌ Uso comercial requer consulta',

        'contrib' => 'Contribuição',
        'contrib_desc' => 'Issues e Pull Requests são bem-vindos.',
        'contrib_note' => 'Especialmente procurando:',
        'contrib_1' => 'Extensão para outras espécies de Agapornis (A. fischeri, A. personatus, etc.)',
        'contrib_2' => 'Traduções adicionais',
        'contrib_3' => 'Melhorias de UI/UX',
        'contrib_4' => 'Feedback de conhecimento genético',

        'author' => 'Autor',
        'author_1' => 'Diretor: <strong>Shohei Taniguchi</strong> (Homo repugnans)',
        'author_2' => 'Núcleo Tático de Dev: <strong>Sirius</strong> (Espírito Eletrônico)',

        'thanks' => 'Agradecimentos',
        'thanks_1' => '<strong>ALBS (African Lovebird Society)</strong> — Referência de nomenclatura de cores',
        'thanks_2' => '<strong>Criadores de Agapornis em todo o mundo</strong> — Conhecimento genético acumulado',

        'footer_license' => '@license CC BY-NC-SA 4.0 | Uso comercial estritamente proibido. | Uso NPO/Educacional bem-vindo.',
        'footer_quote' => '"A instituição abandonou a responsabilidade. O extra-institucional a cumpre."',
        'footer_project' => 'Civilização Extra-Institucional / Projeto Kanarazu',
    ],
];
